### ISSUE TITLE
Bring out Weimer files required for initialization

### ISSUE THREAD

**Issue by twfang** [SWPC-IPE/IPE#33]
There are several files that Weimer 2005 model relies on. Currently, they are opened every time step within the empirical model package or within the dynamo package. These files should be opened in IPE_Forcing_Class.F90 or IPE_Model_Class.F90 instead.

**Comment by ZhuxiaoLi66** [comment]
this moring, I very briefly went through the IPE code for the current issue. 
the current code pathes in ipelib are:
a. dynamo/module_weimer2005IPE ->dynamo/module_hightlat ->IPE_Electrodynamics_Class.F90->IPE_model_Class.F90
b. empirical_efeild/efield_ipe.f ->IPE_Electrodynamics_Class.F90 ->IPE_model_Class.F90

**Comment by ZhuxiaoLi66** [comment]
@twfang   since I am not familiar with IPE_model_Class.F90,  would like to know that can we avoid the reading at every timestep if we put the readings in IPE_model_Class.F90, ? 
I checked the code and the files which has been read in IPE_model_Class.F90, they seems all are HDF5 files, at present, all weimer2005 initial files are .txt files . would like to know is it a proper place to read in the weimer2005 initial files and who has the experience to add some input files to this subroutine (it is perfect if you have), I think maybe it is more effeciency to also inlcude that person on this. I will try to help anyway.

**Comment by twfang** [comment]
They can also be included in IPE_forcing_class.F90. I will work on this when I get a chance. I just would like to keep you in the loop in case we need to test it later. Thanks for looking into this.

**Comment by ZhuxiaoLi66** [comment]
@twfang sounds good.
